packages:
  - "apps/*"
  - "packages/*"

onlyBuiltDependencies:
  - "@prisma/client"
  - "@prisma/engines"
  - prisma
  - unrs-resolver
  - esbuild

allowBuilds:
  "@prisma/client": true
  "@prisma/engines": true
  prisma: true
  unrs-resolver: true
  esbuild: true
